# Generated by Django 6.1 on 2026-09-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_usuario_apellido'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('estado_espacio', models.IntegerField(default=1, help_text='Código de estado (redundante con tipo_estado, tal como en el DER).')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de estado (espacio)',
                'verbose_name_plural': 'Tipos de estado (espacio)',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado_reserva', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de estado (reserva)',
                'verbose_name_plural': 'Tipos de estado (reserva)',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField()),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='estacionamiento.espacio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.AddField(
            model_name='espacio',
            name='tipo_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='estacionamiento.tipoestadoespacio'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_reserva', models.IntegerField(default=1, help_text='Código de estado (redundante con tipo_estado_reserva, tal como en el DER).')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='estacionamiento.espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.usuario')),
                ('tipo_estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='estacionamiento.tipoestadoreserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='espacio',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='estacionamiento.zona'),
        ),
        migrations.AlterUniqueTogether(
            name='espacio',
            unique_together={('zona', 'numero')},
        ),
    ]
