# Generated by Django 6.1 on 2026-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacio',
            old_name='tipo_estado',
            new_name='tipo_estado_espacio',
        ),
        migrations.AlterField(
            model_name='espacio',
            name='estado_espacio',
            field=models.IntegerField(default=1, help_text='Código de estado (redundante con tipo_estado_espacio, tal como en el DER).'),
        ),
    ]
