# Generated by Django 6.1.1 on 2026-09-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_remove_espacio_estado_espacio_and_more'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='patente',
            field=models.CharField(default='SIN CHAPA', max_length=15),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='vehiculos.vehiculo'),
        ),
    ]
