# Generated by Django 6.1.1 on 2026-09-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_movimiento_patente_alter_movimiento_vehiculo'),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='facultad',
            field=models.ForeignKey(help_text='Obligatoria para zonas nuevas (ver ZonaForm). Puede haber zonas viejas sin facultad hasta que se completen a mano.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='universidad.facultad'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='patente',
            field=models.CharField(max_length=15),
        ),
    ]
