# Generated by Django 6.1.1 on 2026-09-29 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_zona_facultad_alter_movimiento_patente'),
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text="Dejar en 'Ninguna' para que sea una zona pública, sin restricción de facultad.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='universidad.facultad'),
        ),
    ]
