# Generated by Django 6.1.1 on 2026-10-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0005_alter_zona_facultad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='estado_reserva',
        ),
    ]
