# Generated by Django 6.1 on 2026-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0006_remove_reserva_estado_reserva'),
        ('usuarios', '0003_usuario_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='tipos_usuario_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Tipos de usuario (Docente, Estudiante, etc.) que pueden usar esta zona, dentro de los que pertenecen a la facultad de arriba. Vacío = cualquier tipo de esa facultad puede entrar. Sin sentido (y no permitido) en una zona sin facultad.', related_name='zonas_permitidas', to='usuarios.tipousuario'),
        ),
    ]
