# Generated by Django 6.1.1 on 2026-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nro_licencia',
            field=models.IntegerField(blank=True, help_text='Número de licencia de conducir (si aplica).', null=True),
        ),
    ]
