# Generated by Django 6.1 on 2026-09-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=150),
            preserve_default=False,
        ),
    ]
