# Generated by Django 6.1.1 on 2026-09-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
        ('usuarios', '0002_usuario_fecha_nacimiento_usuario_nro_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(blank=True, help_text='Obligatoria para Docente, Estudiante y Funcionario (ver Usuario.requiere_facultad).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='universidad.facultad'),
        ),
    ]
