# Generated by Django 6.1 on 2026-09-15 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('horario', models.TimeField(help_text='Hora de referencia de la regla (ej. inicio de franja horaria).')),
                ('tolerancia', models.IntegerField(help_text='Tolerancia en minutos.')),
                ('condicion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Regla de acceso',
                'verbose_name_plural': 'Reglas de acceso',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_por_hora', models.FloatField()),
                ('vigencia', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='usuarios.tipousuario')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuarioRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglas.reglaacceso')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipousuario')),
            ],
            options={
                'verbose_name': 'Regla por tipo de usuario',
                'verbose_name_plural': 'Reglas por tipo de usuario',
                'unique_together': {('regla', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='reglaacceso',
            name='tipos_usuario',
            field=models.ManyToManyField(related_name='reglas_acceso', through='reglas.TipoUsuarioRegla', to='usuarios.tipousuario'),
        ),
    ]
