# Generated by Django 6.1.1 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anho',
            field=models.IntegerField(default=2020, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='cedula_verde',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='chassis',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(default='Sedan', max_length=50),
            preserve_default=False,
        ),
    ]
